# Generated by Django 5.2.5 on 2025-09-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_name', models.CharField(max_length=15)),
                ('user_name', models.CharField(max_length=100)),
                ('weapon_trainer', models.CharField(max_length=100)),
                ('weapon_available', models.IntegerField()),
            ],
        ),
    ]
