# Generated by Django 5.2.5 on 2025-10-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('will', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='weapon_available',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
